### ISSUE TITLE
Failed to setup loop device: No such file or directory

### ISSUE THREAD

**Issue by mikevanis** [guysoft/CustomPiOS#70] opened 2020-04-16 10:21 UTC
I'm trying to generate a distro with CustomPiOS on Ubuntu 18.04 under VirtualBox. Here are the steps I'm currently taking:

1. Clone this repo
2. Use `build_custom_os` script to generate a distro called `test`
3. Add a few modules in `test/src/config`
4. Run ``docker run -v `pwd`:/distro --device /dev/loop-control -it -t guysoft/custompios:devel build`` whilst in `test/src` directory

It successfully expands the image file, changes the partition, but fails when it tries to mount the image with losetup.

```
losetup -f --show -o 272629760 2020-02-13-raspbian-buster-lite.img
losetup: 2020-02-13-raspbian-buster-lite.img: failed to set up loop device: No such file or directory
```

**Comment by guysoft** [comment] 2020-04-22 08:54
Duplicate of #55

**Closed by guysoft** 2020-04-22 08:54 UTC
